### ISSUE TITLE
Apt-Dater manager and host installed -> hosts.conf empty

### ISSUE THREAD

**Issue by e-it** [gnubila-france/puppet-apt_dater#2]
Hello,

I configured apt-dater-manager using the following description:

```
node 'puppet' {
class { 'apt_dater': role => 'manager', manager_ssh_key => template('site/apt-dater.priv.key'); }
}
```

Then I added a host

```
class { 'apt_dater': customer => 'Test', ssh_key_type => 'ssh-rsa', ssh_key => template('site/apt-dater.pub.key'); }
```

Well, that works already - apt-dater and apt-dater-host are being installed - but if I want to start apt-dater I'm getting this error:

> Error on loading config file /root/.config/apt-dater/hosts.conf

The file itself exists:

```
 -rw------- 1 root root 0 Jan 11 22:00 /root/.config/apt-dater/hosts.conf
```

But the file is empty

How can I add the configured hosts automatically?

**Comment by gwarf** [comment]
Hello,
The hosts.conf file is populated using a script working on file created using exported/collected resources, on the manager node `$apt_dater::manager_fragments_dir` should contain a file by manged host, do they exist? 
When using puppet 4 it is under /opt/puppetlabs/puppet/cache/apt-dater-fragments/, with puppet 3 it should be something like /var/lib/puppet/apt-dater-fragments.
If they exist the final hosts.conf file should be created by the /usr/local/bin/update-apt-dater-hosts script.

**Comment by e-it** [comment]
Hello,

this is my result:

```
[root@puppet apt-dater-fragments]# pwd
/var/lib/puppet/apt-dater-fragments
[root@puppet apt-dater-fragments]# ll
insgesamt 0
[root@puppet apt-dater-fragments]# 
```

Obviously there are no fragment files saved in this directory. What could be the reason?

**Comment by gwarf** [comment]
Hi,
Did you enable storedconfigs/puppetdb ? It is required for exported resources, see https://docs.puppetlabs.com/puppet/3.8/reference/lang_exported.html for puppet 3.8.
What are the version of puppet and what is the Operating System?

**Comment by e-it** [comment]
Hello gwarf,

thanks for your answer. Well, I'm running puppet with foreman. I did not install puppetdb manually.

Is it save to install puppetdb on the same host puppet and foreman is running on?

**Comment by gwarf** [comment]
I have never tested foreman, so I don't know... You could try to check this: http://projects.theforeman.org/projects/foreman/wiki/FAQ#How-does-Foreman-work-with-PuppetDB.
One other thing you could try is to add some simple code making use of exported resources, that would allow you to test if they are working and confirm/infirm if it is a bug with this module.
I am only using this code using a standard puppet 4 Open Source installation, but as the code was previously made for puppet3 it should probably still work.

**Comment by gwarf** [comment]
From http://theforeman.org/manuals/1.1/index.html it seems that you can setup puppetdb with foreman 1.1
