### ISSUE TITLE
Invalid resource type sudo::directive

### ISSUE THREAD

**Issue by e-it** [gnubila-france/puppet-apt_dater#3]
Hello,

I've got another problem:

I would like to use the [apt-dater module](https://forge.puppetlabs.com/gnubilafrance/apt_dater).

To do so I included the following:

```
    class { 'apt_dater': customer => 'Test', ssh_key_type => 'ssh-rsa', ssh_key => template('site/apt-dater.pub.key'); }
```

But if I do puppet agent -t I'm getting this error:

> Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Puppet::Parser::AST::Resource failed with error ArgumentError: Invalid resource type sudo::directive at /etc/puppet/modules/apt_dater/manifests/host.pp:56 on node pp-test
> Warning: Not using cache on failed catalog
> Error: Could not retrieve catalog; skipping run

The content of the line is:

```
  sudo::directive { 'apt-dater':
    content => "${apt_dater::host_user} ALL=NOPASSWD: ${apt_dater::host_update_cmd}\n";
  }
```

What can I do here?

**Comment by gwarf** [comment]
Hello,
This modules assumes that a module compatible (ie using the same syntax) with the example42/sudo module is used, I added example42/sudo to the dependencies of the metadata.json, it was missing, if you install it, it should work.
